../rtl/alarm.sv
../rtl/alarm_clock_controller.sv
../rtl/ct_mod_N.sv
../rtl/lcd_int3.sv
../rtl/month_adv_logic.sv
../rtl/month_date_counter28.sv
../rtl/month_date_counter30.sv
../rtl/month_date_counter31.sv
../rtl/negedge_pulse.sv
../rtl/posedge_pulse.sv
../rtl/struct_diag.sv
../testbench/lab2_3_tb.sv
